import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
// Removed FaCheckCircle and other unused Kanban icons from the import list
import {  FaUser, FaTools, FaWrench, FaTags, FaClock, FaCalendarAlt, FaGasPump, FaSpinner } from 'react-icons/fa';
import apiClient from '../utils/apiClient';

// --- Status Choices (Must match Django's JobCard.STATUS_CHOICES) ---
const STATUS_CHOICES = [
    { value: 'OPEN', label: 'Open Job' },
    { value: 'IN_PROGRESS', label: 'In Progress' },
    { value: 'READY_FOR_PICKUP', label: 'Ready for Pickup' },
    { value: 'PAID', label: 'Paid/Closed' },
];
// -------------------------------------------------------------------


const JobCardForm = ({ onCancel }) => {
    const navigate = useNavigate();

    // Data States
    const [clients, setClients] = useState([]); 
    const [vehicles, setVehicles] = useState([]);

    // Form States
    const [selectedClientId, setSelectedClientId] = useState('');
    const [selectedVehicleId, setSelectedVehicleId] = useState('');
    const [formData, setFormData] = useState({
        // job_number is often generated by the backend, so we initialize it empty
        date_in: new Date().toISOString().split('T')[0], 
        initial_odometer: '',
        fuel_level: 50, 
        customer_complaint: '',
        assigned_technician: '', 
        status: 'OPEN', 
    });
    
    // UI States
    const [isLoading, setIsLoading] = useState(false);
    const [isFetchingClients, setIsFetchingClients] = useState(true);
    const [isFetchingVehicles, setIsFetchingVehicles] = useState(false);
    const [error, setError] = useState(null);
    // Removed unused state: [draggedJobId, setDraggedJobId] = useState(null);


    // --- 1. Fetch ALL Clients on component mount ---
    useEffect(() => {
        const fetchClients = async () => {
            setIsFetchingClients(true);
            try {
                const res = await apiClient.get('/clients/'); 
                setClients(res.data.results || res.data);
                setError(null);
            } catch (err) {
                console.error("Failed to fetch clients:", err);
                setError('Could not load clients list. Check API.');
            } finally {
                setIsFetchingClients(false);
            }
        };
        fetchClients();
    }, []); 

    // --- 2. Fetch Vehicles when selectedClientId changes ---
    useEffect(() => {
        if (!selectedClientId) {
            setVehicles([]);
            setSelectedVehicleId('');
            return;
        }

        const fetchVehiclesByClient = async () => {
            setIsFetchingVehicles(true);
            setVehicles([]); // Clear previous vehicles
            setSelectedVehicleId('');
            try {
                const res = await apiClient.get(`/clients/${selectedClientId}/vehicles/`); 
                setVehicles(res.data.results || res.data);
                setError(null);
            } catch (err) {
                console.error(`Failed to fetch vehicles for client ${selectedClientId}:`, err);
                setError('Could not load vehicles for the selected client.');
            } finally {
                setIsFetchingVehicles(false);
            }
        };

        fetchVehiclesByClient();
    }, [selectedClientId]);


    // --- Handlers ---

    const handleChange = (e) => {
        const { name, value } = e.target;
        setFormData(prev => ({ ...prev, [name]: value }));
    };

    const handleClientChange = (e) => {
        // This will trigger the useEffect to fetch vehicles
        setSelectedClientId(e.target.value); 
    };

    const handleVehicleChange = (e) => {
        setSelectedVehicleId(e.target.value);
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        setError(null);
        setIsLoading(true);

        if (!selectedClientId || !selectedVehicleId) {
            setError("Please select both a Client and a Vehicle.");
            setIsLoading(false);
            return;
        }

        // 1. Prepare data for API
        const apiData = {
            ...formData,
            client: parseInt(selectedClientId, 10),
            vehicle: parseInt(selectedVehicleId, 10),
            // Ensure numbers are numbers
            initial_odometer: parseInt(formData.initial_odometer, 10),
            fuel_level: parseInt(formData.fuel_level, 10), 
            // Optional/Mocked fields
            assigned_technician: formData.assigned_technician || null, 
        };
        
        // Remove empty strings for optional fields if the backend serializer expects null/omission
        Object.keys(apiData).forEach(key => {
            if (apiData[key] === '') {
                delete apiData[key];
            }
        });

        try {
            // 2. POST to the JobCardViewSet endpoint
            const response = await apiClient.post('/jobcards/', apiData);
            
            const newJob = response.data;
            // The API response should include the vehicle data linked via the relationship
            const vehiclePlate = newJob.vehicle ? newJob.vehicle.license_plate : 'N/A'; 
            
            const successMessage = `Job Card **${newJob.job_number || newJob.id}** for ${vehiclePlate} created successfully!`;

            // 3. Navigate back to the Kanban board with a success message
            navigate('/jobcards/kanban', { 
                state: { 
                    successMessage: successMessage 
                } 
            });

        } catch (err) {
            console.error("Job Card creation failed:", err.response ? err.response.data : err.message);
            
            let displayMessage = "Failed to create Job Card. Please check data.";
             if (err.response && err.response.data) {
                const errorData = err.response.data;
                // Simple error parsing (you can expand this as needed)
                if (errorData.customer_complaint) {
                     displayMessage = `Complaint Error: ${errorData.customer_complaint.join(' ')}`;
                } else if (errorData.initial_odometer) {
                     displayMessage = `Odometer Error: ${errorData.initial_odometer.join(' ')}`;
                }
            }
            
            setError(displayMessage);
            
        } finally {
            setIsLoading(false);
        }
    };

    // --- Render Logic ---

    if (isFetchingClients) {
        return (
            <div className="loading-page-center">
                <FaSpinner className="spinner" size={30} />
                <p>Loading Clients and Setup Data...</p>
            </div>
        );
    }
    
    if (error && !isLoading) {
        // If the initial client fetch failed, show a dedicated error
        if (isFetchingClients) {
            return <div className="form-page-container"><div className="form-error-message">{error}</div></div>;
        }
    }


    return (
        <div className="form-page-container">
            <header className="page-header">
                <h2><FaWrench style={{ marginRight: '8px' }} /> Create New Job Card</h2>
            </header>
            
            <form onSubmit={handleSubmit} className="app-form">
                {error && <div className="form-error-message">{error}</div>}

                <div className="form-section-header">
                    <FaUser /> Client & Vehicle Selection
                </div>
                
                <div className="form-row-grid">
                    {/* Client Dropdown */}
                    <div className="form-group">
                        <label htmlFor="client">Client Name *</label>
                        <select
                            id="client"
                            value={selectedClientId}
                            onChange={handleClientChange}
                            required
                        >
                            <option value="">-- Select Client --</option>
                            {clients.map(client => (
                                <option key={client.id} value={client.id}>
                                    {/* Assuming API provides client name fields directly (first_name, company_name) */}
                                    {client.company_name || `${client.first_name} ${client.last_name}`}
                                </option>
                            ))}
                        </select>
                    </div>

                    {/* Vehicle Dropdown */}
                    <div className="form-group">
                        <label htmlFor="vehicle">Vehicle License Plate *</label>
                        <select
                            id="vehicle"
                            value={selectedVehicleId}
                            onChange={handleVehicleChange}
                            required
                            disabled={!selectedClientId || isFetchingVehicles}
                        >
                            <option value="">
                                {isFetchingVehicles ? 'Loading Vehicles...' : '-- Select Vehicle --'}
                            </option>
                            {vehicles.map(vehicle => (
                                <option key={vehicle.id} value={vehicle.id}>
                                    {/* Assuming API provides vehicle fields (license_plate, make, model) */}
                                    {vehicle.license_plate} - {vehicle.make} {vehicle.model}
                                </option>
                            ))}
                        </select>
                        {isFetchingVehicles && <FaSpinner className="spinner-small" />}
                    </div>
                </div>

                <div className="form-section-header">
                    <FaTools /> Job Details
                </div>

                <div className="form-row-grid">
                    {/* Date In */}
                    <div className="form-group">
                        <label htmlFor="date_in"><FaCalendarAlt /> Check-In Date *</label>
                        <input
                            type="date"
                            id="date_in"
                            name="date_in"
                            value={formData.date_in}
                            onChange={handleChange}
                            required
                        />
                    </div>
                    
                    {/* Odometer */}
                    <div className="form-group">
                        <label htmlFor="initial_odometer"><FaGasPump /> Odometer Reading *</label>
                        <input
                            type="number"
                            id="initial_odometer"
                            name="initial_odometer"
                            value={formData.initial_odometer}
                            onChange={handleChange}
                            placeholder="e.g., 150000"
                            required
                        />
                    </div>
                    
                    {/* Fuel Level */}
                    <div className="form-group">
                        <label htmlFor="fuel_level"><FaGasPump /> Fuel Level: {formData.fuel_level}%</label>
                        <input
                            type="range"
                            id="fuel_level"
                            name="fuel_level"
                            min="0"
                            max="100"
                            step="25"
                            value={formData.fuel_level}
                            onChange={handleChange}
                            className="range-slider"
                        />
                    </div>
                    
                    {/* Status (Defaulted to OPEN) */}
                    <div className="form-group">
                        <label htmlFor="status"><FaTags /> Initial Status</label>
                        <select
                            id="status"
                            name="status"
                            value={formData.status}
                            onChange={handleChange}
                        >
                            {STATUS_CHOICES.map(status => (
                                <option key={status.value} value={status.value}>
                                    {status.label}
                                </option>
                            ))}
                        </select>
                    </div>
                </div>

                {/* Customer Complaint */}
                <div className="form-group full-width">
                    <label htmlFor="customer_complaint"><FaClock /> Customer Complaint / Work Requested *</label>
                    <textarea
                        id="customer_complaint"
                        name="customer_complaint"
                        value={formData.customer_complaint}
                        onChange={handleChange}
                        rows="4"
                        placeholder="e.g., Vehicle overheating, oil change, strange noise from the rear."
                        required
                    ></textarea>
                </div>
                
                {/* Technician */}
                <div className="form-group full-width">
                    <label htmlFor="assigned_technician"><FaWrench /> Assigned Technician (ID or Name)</label>
                    <input
                        type="text" // Should ideally be a dropdown/lookup for Technician models
                        id="assigned_technician"
                        name="assigned_technician"
                        value={formData.assigned_technician}
                        onChange={handleChange}
                        placeholder="Enter Technician ID (e.g., 1) or Name"
                    />
                </div>


                <div className="form-actions">
                    <button type="submit" className="btn-primary" disabled={isLoading || !selectedVehicleId}>
                        {isLoading ? (<span><FaSpinner className="spinner-small" /> Saving...</span>) : 'Create Job Card'}
                    </button>
                    <button type="button" className="btn-secondary" onClick={onCancel} disabled={isLoading}>
                        Cancel
                    </button>
                </div>
            </form>
            
            {/* --- Form CSS (Embed for simplicity) --- */}
            <style jsx>{`
                .form-page-container {
                    max-width: 900px;
                    margin: 0 auto;
                    padding: 20px;
                }
                .loading-page-center {
                    text-align: center;
                    padding: 50px;
                }
                .app-form {
                    background: #ffffff;
                    padding: 30px;
                    border-radius: 8px;
                    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.05);
                }
                .form-section-header {
                    font-size: 16px;
                    font-weight: 700;
                    color: #4B5563;
                    margin: 20px 0 10px 0;
                    padding-bottom: 5px;
                    border-bottom: 2px solid #F3F4F6;
                    display: flex;
                    align-items: center;
                    gap: 8px;
                }
                .form-row-grid {
                    display: grid;
                    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                    gap: 20px;
                    margin-bottom: 20px;
                }
                .form-group {
                    display: flex;
                    flex-direction: column;
                    position: relative; /* For spinner alignment */
                }
                .full-width {
                    grid-column: 1 / -1;
                }
                .form-group label {
                    font-weight: 600;
                    margin-bottom: 5px;
                    color: #374151;
                    display: flex;
                    align-items: center;
                    gap: 5px;
                }
                .app-form input[type="text"], 
                .app-form input[type="number"],
                .app-form input[type="date"],
                .app-form select,
                .app-form textarea {
                    padding: 10px;
                    border: 1px solid #D1D5DB;
                    border-radius: 4px;
                    font-size: 14px;
                    width: 100%;
                    box-sizing: border-box;
                    transition: border-color 0.2s;
                }
                .app-form input:focus, .app-form select:focus, .app-form textarea:focus {
                    border-color: #6366F1;
                    outline: none;
                }
                .app-form textarea {
                    resize: vertical;
                }
                .form-actions {
                    margin-top: 30px;
                    border-top: 1px solid #F3F4F6;
                    padding-top: 20px;
                    display: flex;
                    justify-content: flex-end;
                    gap: 10px;
                }
                .btn-primary, .btn-secondary {
                    padding: 10px 20px;
                    border-radius: 4px;
                    cursor: pointer;
                    font-weight: 600;
                    transition: background-color 0.2s;
                }
                .btn-primary {
                    background-color: #6366F1;
                    color: white;
                    border: none;
                    display: flex;
                    align-items: center;
                    gap: 8px;
                }
                .btn-primary:hover:not(:disabled) {
                    background-color: #4F46E5;
                }
                .btn-secondary {
                    background-color: #E5E7EB;
                    color: #374151;
                    border: 1px solid #D1D5DB;
                }
                .btn-secondary:hover:not(:disabled) {
                    background-color: #D1D5DB;
                }
                .btn-primary:disabled {
                    opacity: 0.6;
                    cursor: not-allowed;
                }
                .form-error-message {
                    padding: 10px;
                    margin-bottom: 15px;
                    background-color: #FEE2E2;
                    color: #B91C1C;
                    border: 1px solid #FCA5A5;
                    border-radius: 4px;
                }
                
                /* Range Slider Styling */
                .range-slider {
                    -webkit-appearance: none;
                    height: 8px;
                    background: #D1D5DB;
                    border-radius: 4px;
                    margin-top: 5px;
                }
                .range-slider::-webkit-slider-thumb {
                    -webkit-appearance: none;
                    appearance: none;
                    width: 18px;
                    height: 18px;
                    border-radius: 50%;
                    background: #6366F1;
                    cursor: pointer;
                }
                
                /* Spinners */
                .spinner {
                    animation: spin 1s linear infinite;
                    margin-bottom: 10px;
                    color: #6366F1;
                }
                .spinner-small {
                    animation: spin 1s linear infinite;
                    font-size: 1em;
                    margin-left: 8px;
                }
                @keyframes spin {
                    0% { transform: rotate(0deg); }
                    100% { transform: rotate(360deg); }
                }
            `}</style>
        </div>
    );
};

export default JobCardForm;